apiVersion: v1
kind: Service
metadata:
  name: mon-express-service
spec:
  selector:
    app: mon-express
  type: NodePort
  ports:
    - protocol: TCP
      port: 3400
      targetPort: 3400
      nodePort: 30080
